Pull_1
Tatarhontas/JS_hw pull request #1
Opened 2024-05-25 06:43 UTC by Tatarhontas

Привет-привет)

2024-05-25 12:12 UTC, anatoly-karpovich requested changes

2024-05-25 12:12 UTC, anatoly-karpovich commented on 3-JS/task_3.js
> +let nnn = String(n).repeat(3);
Better use const in this task

2024-05-25 12:12 UTC, anatoly-karpovich commented on 3-JS/task_3.js
> +if (Number.isInteger && n >= 1 && n <= 9) {
Number.isInteger need to use like this:
if(Number.isInteger(n)) to return boolean result for particular n variable

2024-05-26 13:49 UTC, VladimirLQA approved these changes
Well done

2024-05-26 14:08 UTC, merged