HW-6
Tatarhontas/JS_hw pull request #4
Opened 2024-06-06 16:04 UTC by Tatarhontas

2024-06-06 16:22 UTC, anatoly-karpovich requested changes

2024-06-06 16:22 UTC, anatoly-karpovich commented on 6-JS/task_2.js
> +            massivMaxWords = [words[i]];                // положили в массив макс слово
```suggestion
            massivMaxWords.length = 0;             massivMaxWords.push([words[i]]);                // положили в массив макс слово
```

2024-06-06 16:22 UTC, anatoly-karpovich commented on 6-JS/task_2.js
> +    let massivMaxWords = [];
```suggestion
    const massivMaxWords = [];
```

2024-06-06 16:22 UTC, anatoly-karpovich commented on 6-JS/task_2.js
> +function delDuplicates (numbers) {
```suggestion
function removeDuplicates (numbers) {
```
Не надо сокращать, функция должна иметь конкретное и понятное название

2024-06-06 16:22 UTC, anatoly-karpovich commented on 6-JS/task_2.js
> +       }
```suggestion
      const result = []
for(const num of numbers) {
if(!result.includes(num)) result.push(num)
      }
return result
} 
```

2024-06-06 16:22 UTC, anatoly-karpovich commented on 6-JS/task_2.js
> +function word1Naoborot (str) {
```suggestion
function reverseWord (str) {
```

2024-06-06 16:22 UTC, anatoly-karpovich commented on 6-JS/task_2.js
> +}
```suggestion
  return  word1 === word1Naoborot (word1) 
} 
```

2024-06-06 16:22 UTC, anatoly-karpovich commented on 6-JS/task_2.js
> +} palindrom (str);
```suggestion
} 
console.log(palindrom (str));
```
Ну и при желании текстовку красивую можно вставить)

2024-06-08 18:27 UTC, VladimirLQA submitted a review, later dismissed

2024-06-11 17:56 UTC, VladimirLQA approved these changes

2024-06-11 17:56 UTC, VladimirLQA commented on 6-JS/task_1.js
> +}
```suggestion
       const foundIdx = allNames.indexOf(name);
        if (foundIdx < 0 ) return null;
        return [name, salaries[foundIdx]]; 
}
```

2024-06-12 09:18 UTC, anatoly-karpovich submitted a review, later dismissed
Great job!

2024-06-13 07:30 UTC, VladimirLQA submitted a review, later dismissed

2024-06-13 19:42 UTC, merged